services:

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  uptime:
    image: louislam/uptime-kuma:latest
    container_name: uptime_kuma
    restart: unless-stopped
    volumes:
      - /home/pi/uptime_kuma/data:/app/data
    ports:
      - 3001:3001
  portainer_agent:
    image: portainer/agent:2.19.5
    container_name: portainer_agent
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001

  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    # ports:
    # - "53:53/tcp"
    # - "53:53/udp"
    # - "8080:80/tcp"
    environment:
    - 'TZ=Europe/Paris'
    - 'WEBPASSWORD={{ password }}'
    - 'DNS1=192.168.1.36#5053'
    - 'DNS2=no'
    volumes:
    - '/home/pi/pihole/etc-pihole/:/etc/pihole/'
    - '/home/pi/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped
    dns:
      - "127.0.0.1"
      - "1.1.1.1"
    cap_add:
      - NET_ADMIN
    network_mode: host
  unbound:
    container_name: unbound
    image: klutchell/unbound
    volumes:
     - /home/pi/unbound/config:/etc/unbound/custom.conf.d
     - /home/pi/unbound/root-hints:/var/lib/unbound/root.hints
     - /home/pi/unbound/unbound.log:/var/log/unbound/unbound.log
    ports:
    - "5053:5053/tcp"
    - "5053:5053/udp"
    healthcheck:
      disable: true
    restart: unless-stopped
    logging:
      options:
        max-size: 50m
  home-assistant:
    container_name: home_assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/pi/home_assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host