---
- hosts: homeserver
  become: true
  roles:
    - name: system
      tags:
        - system
    - name: docker
      tags:
        - containers
    - name: jellyfin
      tags:
        - jellyfin
    - name: netplan
      tags:
        - netplan
