---
- name: Update packages
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists

- name: Install essential packages
  package:
    name: "{{ packages }}"
    state: latest

- name: Set the hostname
  hostname:
    name: "{{ hostname }}"
  
- name: Install Samba packages
  package:
    name:
      - samba-common
      - samba
      - samba-client
    state: present

- name: Create Samba user
  shell: "printf '{{ password }}\n{{ password }}\n' | smbpasswd -a -s {{ username }}"
