---
- name: Update packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
    autoremove: true

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  ansible.builtin.reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists

- name: Install essential packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: latest

- name: Set the hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Install Samba packages
  ansible.builtin.package:
    name:
      - samba-common
      - samba
      - samba-client
    state: present
