- name: Copy network configuration file(s) to Ubuntu VM(s)
  template:
    src: Ubuntu_Netplan.j2
    dest: /etc/netplan/01-netcfg.yaml
    owner: root
    group: root
    mode: 0644

- ansible.builtin.meta: flush_handlers

- name: Apply netplan config
  ansible.builtin.command:
    cmd: netplan apply
